{% set name = "rdkit" %}
{% set version = "2023.09.2" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: d6ed9e0cdf231550fa850070be7ea53154d46ec6cf32a9b5fd5fec2d34a60c6b

build:
  number: 1
  skip: true  # [aarch64]
  missing_dso_whitelist:
    - '*/RDKit*dll'  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - jom  # [win]
    - make  # [unix]
    - pkg-config
  host:
    - libboost-python-devel
    - cairo
    - eigen
    - freetype
    - python
    - numpy
    - pillow
    - pandas
  run:
    - cairo
    - python
    - pillow
    - pandas
    - {{ pin_compatible('numpy') }}
    - pycairo
    - matplotlib-base
    - sqlalchemy
    - reportlab

test:
  commands:
    - python -c "import rdkit; assert rdkit.__version__ == '{{ version }}'"
    - if not exist %LIBRARY_INC%\\rdkit\\Catalogs\\Catalog.h exit 1   # [win]
  imports:
    - rdkit
    - rdkit.Avalon
    - rdkit.Chem
    - rdkit.Chem.AllChem
    - rdkit.Chem.rdFreeSASA
    - rdkit.DataManip
    - rdkit.Dbase
    - rdkit.DistanceGeometry
    - rdkit.ForceField
    - rdkit.Geometry
    - rdkit.ML
    - rdkit.Numerics
    - rdkit.SimDivFilters
    - rdkit.VLib
    - rdkit.VLib.NodeLib
    
outputs:
    - name: rdkit
    - name: rdkit-dev
      requirements:
        run:
            - rdkit

about:
  home: http://rdkit.org
  license: BSD-3-Clause
  license_file: license.txt
  summary: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.
  doc_url: http://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - greglandrum
    - pstjohn
    - mcs07
    - jaimergp
