{% set version = "2024.03.4" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  # NOTE(skearnes): Using `rdkit` as the package name conflicts with the `rdkit` subpackage and causes problems; see
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section and
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#implicit-metapackages.
  name: rdkit-meta
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: cbb39098f720748efd50bde9c26df2166dc89197dbdedf9664d0debaf14319ef

  patches:
    - pyproject.patch

build:
  number: 1
  skip: true  # [aarch64]
  missing_dso_whitelist:
    - '*/RDKit*dll'  # [win]

requirements:
  # See https://conda-forge.org/docs/maintainer/knowledge_base/#placing-requirements-in-build-or-host and
  # https://conda-forge.org/docs/maintainer/knowledge_base/#details-about-cross-compiled-python-packages.
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - postgresql                          # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cmake
    - jom   # [win]
    - make  # [unix]
    - pkg-config
  host:
    - cairo
    - eigen
    - freetype
    - libboost-devel
    - libboost-python-devel
    - numpy
    - pandas <2.2
    - pillow
    - pip
    - postgresql
    - python
    - setuptools
    - setuptools_scm >=8

outputs:
  - name: librdkit
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
        - cmake
      host:
        - cairo
        - eigen
        - freetype
        - libboost-devel
        - libboost-python-devel
        - matplotlib-base
        - numpy
        - pandas <2.2
        - pillow
        - pycairo
        - python
        - reportlab
        - sqlalchemy
      run:
        - cairo
        - eigen
        - freetype
        # NOTE(skearnes): The `host` dependencies above are only listed so that this pin is correctly resolved. Without
        # them (or some subset that I haven't narrowed to yet), libboost may be resolved to a higher version than was
        # used for the build in build.sh.
        - {{ pin_compatible('libboost') }}
    about:
      summary: RDKit C++ library
      license: BSD-3-Clause
      license_file: license.txt

  - name: librdkit-dev
    script: install.bat  # [win]
    requirements:
      build:
        - {{ stdlib("c") }}
      run:
        - {{ pin_subpackage('librdkit', exact=True) }}
    test:
      commands:
        - if not exist %LIBRARY_INC%\\rdkit\\Catalogs\\Catalog.h exit 1  # [win]
    about:
      summary: RDKit headers and library used in librdkit
      license: BSD-3-Clause
      license_file: license.txt

  - name: rdkit
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
        - cmake
        - jom   # [win]
        - make  # [unix]
        - pkg-config
      host:
        - cairo
        - eigen
        - freetype
        - libboost-devel
        - libboost-python-devel
        - matplotlib-base
        - numpy
        - pandas <2.2
        - pillow
        - pip
        - postgresql
        - pybind11-stubgen
        - pycairo
        - python
        - reportlab
        - setuptools
        - setuptools_scm >=8
        - sqlalchemy
      run:
        - {{ pin_subpackage('librdkit', exact=True) }}
        - matplotlib-base
        - {{ pin_compatible('numpy') }}
        - pandas
        - pillow
        - pycairo
        - python
        - reportlab
        - sqlalchemy
    test:
      commands:
        - python -c "import rdkit; assert rdkit.__version__ == '{{ version }}'"
      imports:
        - rdkit
        - rdkit.Avalon
        - rdkit.Chem
        - rdkit.Chem.AllChem
        - rdkit.Chem.rdFreeSASA
        - rdkit.DataManip
        - rdkit.Dbase
        - rdkit.DistanceGeometry
        - rdkit.ForceField
        - rdkit.Geometry
        - rdkit.ML
        - rdkit.Numerics
        - rdkit.SimDivFilters
        - rdkit.VLib
        - rdkit.VLib.NodeLib
        - rdkit.Chem.PandasTools
    about:
      summary: RDKit Python bindings
      license: BSD-3-Clause
      license_file: license.txt

  - name: rdkit-postgresql
    script: install.sh   # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - postgresql  # [build_platform != target_platform]
        - cmake
      host:
        - postgresql
      run:
        - {{ pin_subpackage('librdkit', exact=True) }}
        - postgresql
    test:
      commands:
        # Inspired by https://github.com/conda-forge/pgvector-feedstock/blob/main/recipe/bld.bat.
        - initdb -D test_db
        - if errorlevel 1 exit 1                           # [win]
        - pg_ctl -D test_db -l test.log start
        - if errorlevel 1 exit 1                           # [win]
        - createuser --username=%USERNAME% -w -s postgres  # [win]
        - if errorlevel 1 exit 1                           # [win]
        - createdb test
        - if errorlevel 1 exit 1                           # [win]
        - psql -c 'CREATE EXTENSION rdkit' test
        - if errorlevel 1 exit 1                           # [win]
        - pg_ctl -D test_db stop
    about:
      summary: RDKit PostgreSQL cartridge
      license: BSD-3-Clause
      license_file: license.txt

about:
  home: http://rdkit.org
  license: BSD-3-Clause
  license_file: license.txt
  summary: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.
  doc_url: http://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - greglandrum
    - pstjohn
    - mcs07
    - jaimergp
    - skearnes
