{% set name = "rdkit" %}
{% set version = "2024.03.3" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: 52f79c6bf1d446cdb5c86a35de655d96bad0c52a5f4ecbe15f08eaf334e6f76a

  patches:
    - pyproject.patch

build:
  number: 0
  skip: true  # [aarch64]
  missing_dso_whitelist:
    - '*/RDKit*dll'  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - jom  # [win]
    - make  # [unix]
    - pkg-config
  host:
    - libboost-devel
    - libboost-python-devel
    - cairo
    - eigen
    - freetype
    - python
    - numpy
    - pillow
    - pandas <2.2
    - pip
    - setuptools
    - setuptools_scm >=8
    # For rdkit-postgresql.
    - postgresql

outputs:
  - name: librdkit
    script: install.sh  # [unix]
    requirements:
      run:
        - cairo
    test:
      commands:
        # NOTE(skearnes): Set RDK_BUILD_CPP_TESTS=ON in build.sh to compile tests.
        - export RDBASE="$SRC_DIR"
        - ctest --output-on-failure
    about:
      summary: RDKit C++ library
      license: BSD-3-Clause
      license_file: license.txt
  - name: rdkit
    script: install.sh  # [unix]
    requirements:
      build:
        - cmake
      host:
        # For rdkit-stubs.
        - pybind11-stubgen
      run:
        - {{ pin_subpackage('librdkit', exact=True) }}
        - python
        - pillow
        - pandas
        - {{ pin_compatible('numpy') }}
        - pycairo
        - matplotlib-base
        - sqlalchemy
        - reportlab
    test:
      commands:
        - python -c "import rdkit; assert rdkit.__version__ == '{{ version }}'"
      imports:
        - rdkit
        - rdkit.Avalon
        - rdkit.Chem
        - rdkit.Chem.AllChem
        - rdkit.Chem.rdFreeSASA
        - rdkit.DataManip
        - rdkit.Dbase
        - rdkit.DistanceGeometry
        - rdkit.ForceField
        - rdkit.Geometry
        - rdkit.ML
        - rdkit.Numerics
        - rdkit.SimDivFilters
        - rdkit.VLib
        - rdkit.VLib.NodeLib
        - rdkit.Chem.PandasTools
    about:
      summary: RDKit Python bindings
      license: BSD-3-Clause
      license_file: license.txt
  - name: rdkit-dev
    script: install_rdkit_dev.bat  # [win]
    requirements:
      build:
        - {{ stdlib("c") }}
      run:
        - {{ pin_subpackage('rdkit', exact=True) }}
    test:
      commands:
        - if not exist %LIBRARY_INC%\\rdkit\\Catalogs\\Catalog.h exit 1  # [win]
    about:
      summary: RDKit headers and library used in rdkit package
      license: BSD-3-Clause
      license_file: license.txt
  - name: rdkit-postgresql
    script: install.sh  # [unix]
    requirements:
      run:
        - {{ pin_subpackage('librdkit', exact=True) }}
        - postgresql
    test:
      commands:
        - mkdir test_db
        - cd test_db
        - initdb .
        - pg_ctl -D . -l logfile start
        - createdb test
        - psql -c 'create extension rdkit' test
    about:
      summary: RDKit PostgreSQL cartridge
      license: BSD-3-Clause
      license_file: license.txt

about:
  home: http://rdkit.org
  license: BSD-3-Clause
  license_file: license.txt
  summary: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.
  doc_url: http://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - greglandrum
    - pstjohn
    - mcs07
    - jaimergp
